### ISSUE TITLE
Github repo for Avatax Ruby SOAP gem?

### ISSUE THREAD

**Issue by jordan-brough** [avadev/AvaTax-Calc-SOAP-Ruby#8]
Hi there, could you possibly set up a Github repo for the Avatax_TaxService Ruby SOAP gem?  I see you have a github repo for the REST gem [here](https://github.com/avadev/AvaTax-Calc-REST-Ruby) but this AvaTax-Calc-SOAP-Ruby repo only has sample code in it and not the library code.

I've set up an unofficial version using my own github account [here](https://github.com/jordan-brough/Avatax_TaxService) based on the downloaded gem.

There are a couple issues I'd like to submit pull-requests for.  See these commits:
https://github.com/jordan-brough/Avatax_TaxService/compare/3e53d03...234fd9f
but it's harder to submit those without an official Github repo.

Thanks.

**Comment by anyarms** [comment]
Hi Jordan! Let me see where this is actually stored internally and what I can do to get it published more transparently. Your edits look spot on.

**Comment by jordan-brough** [comment]
@anyarms Super!  Thanks.

**Comment by jordan-brough** [comment]
@anyarms any update on this?  It would be great to be able to submit those patches from #9.  If it's not possible to set up a github repo could you perhaps just manually apply those patches for a new release of the gem?  Thanks.

**Comment by anyarms** [comment]
@jordan-brough I'm waiting for internal department approval! I haven't forgotten! Sorry about the wait.

**Comment by anyarms** [comment]
@jordan-brough  Repo is finally up! I'm working on incorporating your changes now.
https://github.com/avadev/AvaTax-SOAP-Ruby-SDK

**Comment by jordan-brough** [comment]
@anyarms that's great news, thank you!  If you'd like me to submit the changes as PRs I'm happy to do so.  Just lmk.  Thanks!

**Comment by anyarms** [comment]
@jordan-brough  That would be amazing! I'll keep an eye out for the PR and push out a new version of the gem.
